neurobagel/workflows

- README.md
- Adds descriptive README.
For bug fixes:
> [DOC] Create README.md

- template_workflows/stale.yml
Closes #3
Closes #
- apply new label for stalebot
- update message in stalebot to explain the new `someday` label and how to triage issues
For bug fixes:
> Update stale.yml label and message

- template_workflows/stale.yml
Closes #30
Closes #
-
-
For bug fixes:
> [FIX] list of labels to ignore

- .github/sync.yml
> Update the list of repositories

- template_configs/.autorc
This is currently breaking the release workflow
For bug fixes:
> [FIX] Fix omit-commits config format in .autorc

- .github/sync.yml
- template_workflows/auto_release/build_docker_on_release.yml
- Closes #45 
- Followed instructions in https://github.com/BetaHuhn/repo-file-sync-action?tab=readme-ov-file#using-templates
- Note use of `latest` tag instead of `stable`
For bug fixes:
> [CI] Add workflow for building Docker image on release

- .github/sync.yml
- template_workflows/auto_release/build_docker_on_release.yml
- Debugging https://github.com/neurobagel/workflows/pull/49
This is a test PR to see the behaviour of GH secret expansion in workflows synchronized using `sync.yml`
For bug fixes:
> [TESTING] Create toy template variables to test secret expansion in workflows

- .github/sync.yml
> Added `query-tool` to auto-release and docker sections of the `sync.yaml`

- .github/dependabot.yml
> [MNT] Add dependabot.yml and configure checks of template workflows

- .github/workflows/global_move_bot_pr_to_board.yml
- Counterpart to https://github.com/neurobagel/planning/issues/46
- also make the workflow handle PRs with the `_community` label (see #33)
-
For bug fixes:
> [INF] Move global_move_bot_pr_to_board.yml from planning repo

- template_workflows/project_automation/handle_external_pr.yml
> [FIX] Add missing GH token

- .github/sync.yml
- template_configs/LICENSE
> [INF] Add LICENSE to auto sync workflow

- README.md
- Testing making changes from a branch on the fork of the repo
For bug fixes:
> [DOC] More details in README

- template_configs/.autorc
- Closes #56 
- We are now omitting commits (PRs) with `skip-release` applied using the same plugin that we use to exclude bot PRs
For bug fixes:
> [FIX] omit commits with skip-release label

- .github/workflows/global_move_community_pr_to_board.yml
- template_workflows/project_automation/handle_external_pr.yml
- Closes https://github.com/neurobagel/planning/issues/148
- Closes #46
-
-
For bug fixes:
> [ENH] Add dedicated workflow for community PRs

- .github/sync.yml
- Closes https://github.com/neurobagel/tools/issues/15
- See also https://github.com/neurobagel/tools/pull/17
-
-
For bug fixes:
> [CI] Add `tools` repo to workflow sync.yml

- template_configs/.autorc
Related to:
- https://github.com/neurobagel/workflows/issues/87
- Remove extra skip keyword for pre-commit CI that has no effect
- Try adding `pre-commit.ci - pr` as required status check to force CHANGELOG PR to wait for it to run
- (Target repo branch rules, e.g. bagel-cli, may also need to be updated to have this as a required status check)
For bug fixes:
> [CI] add pre-commit ci as required status check

- template_configs/.autorc
- template_workflows/auto_release/release.yaml
- Closes #87 (again)
- See https://hackmd.io/CtKRO2k0TYuN198QvAM7MA?both#Notes-from-troubleshooting-automatic-release-workflow for full context
- Instead of using the `protected-branch` plugin, we use a short-lived installation access token from a newly created + installed [Neurobagel Bot app](https://github.com/apps/neurobagel-bot) (which has been added to the list of actors allowed to bypass required PRs) to authenticate at both the `actions/checkout` and release steps
- note: the choice to use the bot is somewhat arbitrary, this should also work with a PAT from an org admin, but this way the release comments are not associated with any specific account and can be clearly differentiated as automated, e.g.:
For …
> [FIX] Bypass required PR rules in release wf

- template_workflows/auto_release/build_docker_on_release.yml
- See https://github.com/neurobagel/workflows/issues/97
- Temporary fix to avoid rollbacks of repo-level updates when the wfs are synced
For bug fixes:
> [MNT] Manually version update `docker/build-push-action`

- .github/sync.yml
> [ENH] Add recipes to group for syncing template release workflows

- template_workflows/auto_release/build_docker_on_release.yml
- See failing https://github.com/neurobagel/api/actions/runs/10375454647 for context
- `DOCKERHUB_REPO` is a repository variable, not a secret
For bug fixes:
> [FIX] Fix reference to `DOCKERHUB_REPO` in build_docker_on_release.yml

- template_workflows/auto_release/build_docker_on_release.yml
- Variables defined for GH Actions should be accessed through the vars context, not the env context !
For bug fixes:
> [FIX] Fix `DOCKERHUB_REPO` access in build_docker_on_release.yml

- .github/sync.yml
> [MNT] Add `neurobagel/ui` to sync.yml

- .github/workflows/add_iss2project.yml
- .github/workflows/global_move_bot_pr_to_board.yml
- .github/workflows/global_move_community_pr_to_board.yml
- Closes #109
- Related to https://github.com/neurobagel/planning/pull/186
For bug fixes:
> [MNT] Replace workflow-specific PATs with Neurobagel Bot app

- .github/sync.yml
- .github/workflows/sync_wf.yml
> [MNT] Update `sync_wf` and `sync.yaml`

- template_configs/.autorc
- See also https://github.com/neurobagel/planning/issues/7
-
-
For bug fixes:
> [REF] Update the auto pr release label colors

- .github/sync.yml
- Fixes currently failing sync wf: https://github.com/neurobagel/workflows/actions/runs/12644813733
- Remove `apis` repo (added in https://github.com/neurobagel/workflows/pull/115) from all sync groups since the repo seems to no longer exist
For bug fixes:
> [FIX] Remove deprecated apis repo from sync.yml

- .github/sync.yml
- Closes #123
- Added `annotation-tool` to the `template_workflows/project_automation/`, `template_workflows/auto_release/release.yaml`, `template_workflows/auto_release/build_docker_on_release.yml`, and  `template_configs/LICENSE` sections of the sync config
- Didn't include `annotation-tool in the `template_workflows/build_docker_nightly.yml` since it will most likely need a custom workflow like the query tool
For bug fixes:
> [MNT] Addd `annotation-tool` repo to the `sync` config file

- .github/sync.yml
- Closes  #126
-
-
For bug fixes:
> [REF] Update sync path to legacy annotator

- template_workflows/auto_release/build_docker_on_release.yml
- template_workflows/build_docker_nightly.yml
- Should fix discrepancy between the current CLI Docker image workflows and the template workflows in https://github.com/neurobagel/bagel-cli/pull/432
For bug fixes:
> [MNT] Add Docker image build for ARM64

- template_workflows/dependabot.yml
Needs a directory to operate on for every config section
- Closes #129 (again)
-
-
For bug fixes:
> [FIX] remaining issues with the dependabot config

- .github/sync.yml
> [MNT] Add react bagel to sync

- template_workflows/project_automation/add_iss2project.yml
- Dependabot has been pushing this across the repos
- Now the sync workflow fights back
- We must upgrade the template wf (that dependabot ignores) to make the upgrade permanent
For bug fixes:
> [MNT] Upgrade actions/create-github-app-token to v2

- .github/sync.yml
- Closes https://github.com/neurobagel/communities/issues/8
For bug fixes:
> [ENH] Add communities repo to sync.yml

- .github/sync.yml
- Fixes regression in https://github.com/neurobagel/bagel-cli/pull/490
- The CLI now has a custom release workflow to push to PyPI, so it should no longer get the template workflow
For bug fixes:
> [MNT] Remove CLI from release config group in sync.yml

- .github/dependabot.yml
- .github/sync.yml
- Related to https://github.com/neurobagel/workflows/issues/55
- When the repo-wide **template** dependabot.yml was introduced in #130, the previously-existing custom dependabot.yml file in this repo (intended for updating the actions in the `template_workflows` directory to prevent version rollbacks) was overridden by the new template on the next sync (https://github.com/neurobagel/workflows/pull/131)
- This is causing the source template workflows to not be updated, leading again to version rollbacks when the sync happens
- To resolve this, this PR removes `workflows` from the sync targets for the template dependabot.yml and updates .github/dependabot.yml in this repo to act on `template_workflows` again
For …
> [FIX] Make Dependabot config (not the template) act on `template_workflows` again
